### ISSUE TITLE
REQUEST: Add project launch_ros_sandbox

### ISSUE THREAD

**Issue by thomas-moulard** [ros-tooling/community#12]
### Description
- What is this tool?

Using `launch_ros_sandbox`, you can define launch files running nodes in restrained environments, such as Docker containers or separate user accounts with limited privileges.

- Motivation for putting under WG umbrella.

Help driving improvements to the ROS 2 launch system, which is a ROS 2 tool.

### Existing URL

https://github.com/ros-tooling/launch_ros_sandbox
https://github.com/ros-tooling/launch_ros_sandbox-release

### Proposed Subproject Owner

@zmichaels11

### Requirements

- [x] Builds on latest ROS2 stable release with no warnings
- [x] Has linters enabled, passes 100% on `colcon test`

**Comment by emersonknapp** [comment]
Approved.
