### ISSUE TITLE
REQUEST: Extend project rosbag2

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/community#19]
### Description
We want to include the `rosbag2_bag_v2` ros 1 bridge plugin officially to the `rosbag2` project on this WG.

This is not a new subproject, but rather categorizes this repository as part of an existing project.

The rationale is that it is tied closely to rosbag2 functionality and was authored by the same contributors.

### Existing URL
https://github.com/ros2/rosbag2_bag_v2

**Comment by Karsten1987** [comment]
+1

just for my understanding: Would it make sense to open these sorts of feature requests as PRs so that people can approve it?

**Comment by emersonknapp** [comment]
Yeah, I think it would make more sense to do it that way, I have found the extra step mildly annoying haha. I think Pull Request templates are a feature on GitHub, I'll try setting that up

**Comment by emersonknapp** [comment]
@Karsten1987 opened https://github.com/ros-tooling/community/pull/20 to try and streamline the workflow, thoughts?

**Comment by emersonknapp** [comment]
Closing - needs to be a PR according to the new PR templates
